config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "billboards#index"

 resources :billboards do 
  resources :songs
 end
 resources :artists do
  resources :songs
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :billboard, optional: true
  belongs_to :artist, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action  :authenticate_user!
end
 

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # before_action :set_billboard, only: [:create]
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
    render partial: "form"
  end

  def create 
    @artist = Artist.new(artist_params)
    if @artist.save
    redirect_to artists_path
   else
    render partial: "form"
   end

  end


  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to artists_path
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end 

  private
  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :avatar)
  end

  # def set_billboard
  #   @billboard =  Billboard.find(params[:id])
  # end

end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :update, :edit, :destroy]

  def index
    @billboards = Billboard.all
  end

  def show
  end

  def new
    @billboard = Billboard.new
    render partial: "form"
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect_to billboards_path
    else
      render :new
    end
  end


  def edit
    render partial: "form"
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to billboards_path
    else
      render :edit
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end

  private
  def set_billboard
    @billboard = Billboard.find(params[:id])
  end

  def billboard_params
    params.require(:billboard).permit(:title)
  end


end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :update, :edit, :destroy]
  def index
    @songs = Song.all
  end

  def show
  end

  def new
    @song = Song.new
    render partial: "form"
  end

  def create
    @song = Song.new(songs.params)
    if 
      @song.save
      redirect_to artist_path
    else 
      render partial: "form" 
  end


  def edit
    render partial: "form"
  end

  def delete
    @song.destroy
  end

  private 
  def set_song
    @songs = Song.find(params[:id])
  end


  def song_params
    params.require(:billboard).permit(:artist)
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h1><%= @artist.id ? "Edit artist" : "Create artist" %></h1>
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.label :avatar %>
  <%= f.text_field :avatar %>
  <%= f.submit %>
  <% end %>

app/views/artists/edit.html.erb
<h1>edit artist</h1>

<%= render "form", artist: @artist %>

<%= link_to "Back", artists_path %>

app/views/artists/index.html.erb
<h1>Top 100 Artist</h1>
<%= link_to "Add a new artist", new_artist_path %>
<ul>
  <% @artists.each do |artist| %>
  <li><%= link_to artist.name, artist_path(artist) %></li>
  <% end %>
  </ul>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= fender "form", billboard: @billboard, artist: @artist %>

<%= link_to "back", artists_path %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<%= link_to "edit artist", edit_artist_path %>
<%= link_to "delete artist", @artist, method: :delete %>
<h2>Songs</h2>

app/views/billboards/_form.html.erb
<h1><%= @billboard.id ? "Edit billboard" : "Create billboard" %></h1>
<%= form_for @billboard do |f| %>
 <div class= "field">
  <%= f.label :title %>
  <%= f.text_field :title, required: true, autofocus: true %>
  <%= f.submit %>
  </div>
  <% end %>

app/views/billboards/artists.html.erb
<h1>Billboards#artists</h1>
<p>Find me in app/views/billboards/artists.html.erb</p>

app/views/billboards/edit.html.erb
<h1>Billboards#edit</h1>
<p>Find me in app/views/billboards/edit.html.erb</p>

app/views/billboards/index.html.erb
<%= button_to "Log Out", destroy_user_session_path, method: :delete %>
<h1 class="ui header">Billboard top 100 artist</h1>
   <%= link_to "New billboard", new_billboard_path %>
   <div class="ui divider"></div>
<table class="ui striped table">
  <thead>
     <tr class="center aligned">
     <th colspan="4"></th>
     </tr>
     </thead>

<tbody>     
  <% @billboards.each do |billboard| %>
    <tr class="center aligned" >

   <h1><%= billboard.title %></h1>
     <td><%= link_to "Artist", artists_path %></td>
     <td><%= link_to "Edit Billboard", edit_billboard_path(billboard) %></td>
       <td><%= link_to "Delete Billboard", billboard_path(billboard), method: :delete %></td>
      </td>
     </tr>
   <% end %>
   </tbody>
   </table>

   <br />

app/views/billboards/new.html.erb
<h1>New billboard</h1>

<%= render "form", billboard: @billboard %>

<%= link_to "Back", billboards_path %>

app/views/billboards/show.html.erb
<h1><%= @billboard.title %></h1>
<div class="ui card">
<div class="image">
<button class="ui basic button"><i class="icon music"></i>
</h1>
<hr />
<%= link_to "Create Artist", new_artist_path(@billboard) %>
<%= link_to "View Artist", artist_path(@billboard) %>
<br />
<%= link_to "Edit Artist", edit_artist_path(@billboard) %>
<br />
<%= link_to "Delete Artist", @billboard, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="ui container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>edit Song</h1>

<%= render "form", song: @song %>

<%= link_to "Back", artists_song_path %>

app/views/songs/index.html.erb
<%= link_to "Add a new song", songs_path %>
<ul>
  <% @songs.each do |song| %>
  <li><%= link_to song.name, artist_song_path(song) %></li>
  <% end %>
  </ul>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>